### PR TITLE
Fixed MenuInfo.cpp to show a maximum sandbox paths when error dialog is ...

### PR DESCRIPTION
**Pull request by flemingg**
Issue #44

### CODE REVIEW

**Comment by gisraeli** [comment]
looks good, somethings I might modify: If we aren't showing all the paths, add something to the beginning that says how many there actually are (ie say showing 10 or 34) or something. Also it doesn't really matter but stylistically I would make the "maxPaths " const (since it is intended to be)

**Comment by KristinaTaylor** [comment]
@gisraeli  did you mean to self-assign?  

We also need to fix the spelling in "IDS_SANDBOX_NOTALLOWED1 "Can't create Sandbox here **becase** the following folder already has a Sandbox:"

Can we also change for pluralization? I'm ok with "following folder(s) have Sandboxes:" rather than putting dynamic smarts in.

**Comment by gisraeli** [comment]
@KristinaTaylor  only because I was reviewing the changes :)

**Comment by gisraeli** [comment]
This pull request ended up being superseded by pull request #52

**Pull request merged**
