### PR TITLE
Setup builds and update installer with build version

### PR DESCRIPTION
**Pull request by bleskows**
Trying to get master to build in AppVeyor using an unstable OS (Visual Studio 2013 CE).

### CODE REVIEW

**Comment by bleskows** [comment]
This is basically the same work as #21 except merging with a clean master. We'll determine if we want to merge this one in, or continue with #21.

Edit: #21 closed since this pull request has the code changes.

**Comment by bleskows** [comment]
Code changes for #4 and #14

**Comment by sharonzhao** [comment]
It works installing the installer on 64 bit windows 7, and the version number for the installer matches the AppVeyor build number. Verified using build 1.0.43.0
Installing the installer on the 32 bit windows 7 platform got error: This installer package is not supported by this processor type. Contact your product vendor. Tested with build 1.0.8.0.

**Comment by bleskows** [comment]
@gisraeli thoughts on the installer failure for 32 bit windows 7?

**Pull request merged**
